package com.ftn.sbnz_2020.facts;

public enum DiseaseCategory {
	INFECTIOUS,
	POISONING,
	CANCER,
	CARDIOVASCULAR,
	NEUROLOGIC,
	EYEDISEASE,
	ENDOCRINE,
	URINAR,
	OTHER,
	BEHAVIORAL,
	ENVIRONMENTAL,
	SKELETAL_AND_MUSCULAR_DISORDER,
	PARASITES,
	BACTERIAL
}
