package drools.spring.rules;

//list any import classes here.
import com.ftn.sbnz_2020.facts.*;


//declare any global variables here




rule "Special rule for canine distemper"
	lock-on-active true
	agenda-group "diagnose"
	salience 30
    when
    	$d: Disease(name=="Canine distemper")
    	$dio: Diagnose($pat: patient)
        $vaccine:Vaccine(name=="DA2P")
    	Number(intValue!=0) from accumulate(
    		$v:Vaccination(
    			this memberOf $pat.vaccinations,
    			vaccine==$vaccine,
    			date>(monthsAgo(-12)),
    			date<(daysAgo(-14))
    		),
    		count($v)
    	)
    then
    	delete($d)
end


