package drools.spring.rules;

//list any import classes here.
import com.ftn.sbnz_2020.facts.*;


//declare any global variables here




rule "Special rule for canine distemper"
	lock-on-active true
	agenda-group "finding symptoms"
	salience 20
    when
    	$dio: Diagnose($pat: patient)
        $vaccine:Vaccine(name=="DA2P")
    	Number(intValue==0) from accumulate(
    		$v:Vaccination(
    			this memberOf $pat.vaccinations,
    			vaccine==$vaccine,
    			date>(monthsAgo(-12))
    		),
    		count($v)
    	)
    then
        System.out.println("prosao vakcine");
end


